# Generated by Django 6.0.4 on 2026-05-15 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_company_name_customuser_job_title'),
        ('diplomas', '0006_diploma_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ine',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='INE / ID National'),
        ),
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.PositiveIntegerField(default=2, verbose_name="Nombre d'ALGO demandés")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to='diplomas.institution')),
            ],
        ),
    ]
