# Generated by Django 6.0.4 on 2026-05-01 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_id_number', models.CharField(max_length=50, verbose_name="Numéro d'étudiant")),
                ('degree_name', models.CharField(max_length=255, verbose_name='Intitulé du diplôme')),
                ('major', models.CharField(blank=True, max_length=255)),
                ('graduation_date', models.DateField()),
                ('unique_identifier', models.CharField(editable=False, max_length=12, unique=True)),
                ('document_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('blockchain_tx_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transaction Algorand')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_diplomas', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='diplomas.institution')),
            ],
        ),
    ]
