# Generated by Django 6.0.4 on 2026-05-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/pdfs/'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='document_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
