# Generated by Django 6.0.4 on 2026-05-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0002_diploma_pdf_file_alter_diploma_document_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
