# Generated by Django 6.0.4 on 2026-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0003_diploma_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='blockchain_address',
            field=models.CharField(blank=True, max_length=58, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='blockchain_mnemonic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='blockchain_private_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
