# Generated by Django 6.0.4 on 2026-05-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0005_verificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('valid', 'Valide'), ('revoked', 'Révoqué')], default='valid', max_length=20),
        ),
    ]
